Updated cards for FCC Feas. Rep. / ESUPP studies.
LHCfitNikhef/smefit_release pull request #84
Opened 2024-07-10 12:26 UTC by arossia94

We collect here all the new runcards used for studies aimed at the FCC Feasibility Report and/or the European Strategy Update.

2024-11-11 11:57 UTC, jacoterh commented
Thanks @arossia94, I'll just merge the rge-interface branch into this one to resolve the conflicts. @LucaMantani and I set up an automatic check to have uniform formatting in the yaml and json files, so we want to have that here too!

2024-11-11 12:13 UTC, jacoterh commented
@arossia94: just so you know, the GitHub pre-commit test didn't like the following yaml file: https://github.com/LHCfitNikhef/smefit_release/blob/20b335dc5a4d6c7c821132c803ca4a6ae65d16f2/runcards/uv_models/UV_scan/Granada/out_UV_dict_Coll_Granada_Mod_28_Mass_1_Tree.yaml

According to GitHub copilot: The issue is caused by the presence of parentheses in the value `0.3580546576383589(L1)(1,1)`. YAML does not support such syntax directly. You need to quote the value to treat it as a string.

```yaml
UV couplings : [gammaL1, gL1B, gL1W, gL1WSM, gL1Wtil, h1L1, h2L1, Conjugate(Sqrt(1 - Power(gammaL1,2))), Im(h3L1), Re(h2L1), Re(h3L1), Subscript(\[Lambda]Hat,\[Phi]), "0.3580546576383589(L1)(1,1)"]
```

I'll fix it manually, but perhaps good to know for Match2Fit as well.

2024-11-11 12:54 UTC, arossia94 commented
> @arossia94: just so you know, the GitHub pre-commit test didn't like the following yaml file: https://github.com/LHCfitNikhef/smefit_release/blob/20b335dc5a4d6c7c821132c803ca4a6ae65d16f2/runcards/uv_models/UV_scan/Granada/out_UV_dict_Coll_Granada_Mod_28_Mass_1_Tree.yaml. You can test this by running `pre-commit run --all-files `

In fact, that model should be removed. It's a troublesome model that requires further manual expansion of the matching relations and we've never fitted it.

2024-11-20 14:51 UTC, jacoterh requested changes
Thanks for updating the UV cards to account for Op @arossia94! I have just one small request before we merge, could you remove everywhere the .dummy file?

2024-11-20 14:51 UTC, jacoterh commented on runcards/uv_models/Mass_scan/Fitmaker/dummy
This dummy file can be removed, same for the others

2024-11-20 15:38 UTC, arossia94 commented on runcards/uv_models/Mass_scan/Fitmaker/dummy
I just removed the 3 dummy files.

2025-09-25 08:59 UTC, LucaMantani commented
I think we don't need to collect these old cards, they even have the old datasets format...

2025-09-25 08:59 UTC, closed without merging